# linux
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias git='sudo git'
alias apt-sources="grep -r --include '*.list' '^deb ' /etc/apt/sources.list*"
PATH=$PATH:~/.local/bin
source ~/.bash_profile
