export ZSH=~/.oh-my-zsh

ZSH_THEME="shellectric"
DISABLE_AUTO_TITLE="true"
plugins=(
  docker
  fzf-zsh
  gem
  git
  heroku
  httpie
  npm
  pip
  poetry
  python
  vagrant
  wd
  web-search
  zsh-autosuggestions
  zsh-syntax-highlighting
)
source ~/dotfiles/dot/zsh/autocomplete.zsh
source ~/dotfiles/dot/zsh/syntax_highlighting.zsh
source $ZSH/oh-my-zsh.sh
source ~/dotfiles/dot/zsh/yoink_from_bash.zsh
alias rc='exec zsh'
alias fresh="omz update && fresh"

timezsh() {
  shell=${1-$SHELL}
  for i in $(seq 1 10); do /usr/bin/time $shell -i -c exit; done
}

# name tab by dir
function precmd {
  printf "\033]0;%s\a" "$(basename $(pwd))"
}

export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
export PATH="${PATH}:${HOME}/.oh-my-zsh/custom/plugins/fzf/bin/fzf"

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh

if [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
  source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ ! -d "${ZSH}/plugins/poetry" ]; then
  mkdir "${ZSH}/plugins/poetry"
fi
if [ -x "$(command -v poetry)" ]; then
  poetry completions zsh > $ZSH/plugins/poetry/_poetry
fi
bindkey "^X^_" redo
