red=$(tput setaf 1)
green=$(tput setaf 2)
orange=$(tput setaf 3)
blue=$(tput setaf 4)
purple=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
bold=$(tput bold)

bright_black=$(tput setaf 8)
bright_red=$(tput setaf 9)
bright_green=$(tput setaf 10)
bright_orange=$(tput setaf 11)
bright_blue=$(tput setaf 12)
bright_purple=$(tput setaf 13)
bright_cyan=$(tput setaf 14)
bright_white=$(tput setaf 15)

reset=$(tput sgr0)
alias reset="tput sgr0"
