red=$(tput setaf 1)
alias red="tput setaf 1"
green=$(tput setaf 2)
alias green="tput setaf 2"
orange=$(tput setaf 3)
alias orange="tput setaf 3"
blue=$(tput setaf 4)
alias blue="tput setaf 4"
purple=$(tput setaf 5)
alias purple="tput setaf 5"
reset=$(tput sgr0)
alias reset="tput sgr0"
